## @file
# Azure Pipeline build file for a build using ubuntu and GCC5
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020, Hewlett Packard Enterprise Development LP. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: makubacki
      name: makubacki/mu_devops
      ref: use_py_virtual_env_on_linux_container_test

variables:
- group: architectures-arm64-x86-64
- group: tool-chain-ubuntu-gcc

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: $(arch_list)
    do_ci_build: true
    do_ci_setup: false
    packages: IpmiFeaturePkg
    target_list: DEBUG,RELEASE,NO-TARGET,NOOPT
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
    container_image: ghcr.io/tianocore/containers/fedora-35-build:latest
    install_tools: false
