## @file
# Azure Pipeline build file for a build using Windows and VS2019
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
# MU_CHANGE [BEGIN]
trigger:
- main

schedules:
- cron: "0 8 * * 0,3"   # Sun/Wed at 1AM Pacific
  displayName: Sun/Wed Build
  branches:
    include:
    - main
  always: true          # Always build, even if no changes

pr:
- main
# MU_CHANGE [END]

jobs:
- template: templates/pr-gate-build-job.yml
  parameters:
    tool_chain_tag: 'VS2019'
    vm_image: 'windows-latest'
    arch_list: "X64"
